export const nodeEnv = process.env.NODE_ENV;
export const isProduction = nodeEnv === 'production';
export const locale = process.env.NEXT_PUBLIC_LOCALE ?? 'en-US';
export const domain = process.env.NEXT_PUBLIC_AUTH0_DOMAIN;
export const clientId = process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID;
export const audience = process.env.NEXT_PUBLIC_AUTH0_AUDIENCE;
export const scope = process.env.NEXT_PUBLIC_AUTH0_SCOPE;
export const redirectUri = process.env.NEXT_PUBLIC_AUTH0_REDIRECT_URI;
export const takeshapeApiKey = process.env.NEXT_PUBLIC_TAKESHAPE_API_KEY;
export const takeshapeApiUrl = process.env.NEXT_PUBLIC_TAKESHAPE_API_URL;
export const stripePublishableKey = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
